/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.k_atk.panel;

import com.k_atk.utills.ConnectionDatabase;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.BorderFactory;

/**
 *
 * @author karel
 */
public class StrukDesign extends javax.swing.JPanel {
    Connection cn = ConnectionDatabase.OpenConnection();
    
    private int totalHarga = 0;
    private int totalBayar = 0;
    private int kembalianBayar = 0;

    public int getTotalHarga() {
        return totalHarga;
    }

    public void setTotalHarga(int totalHarga) {
        this.totalHarga = totalHarga;
    }

    public int getTotalBayar() {
        return totalBayar;
    }

    public void setTotalBayar(int totalBayar) {
        this.totalBayar = totalBayar;
    }

    public int getKembalianBayar() {
        return kembalianBayar;
    }

    public void setKembalianBayar(int kembalianBayar) {
        this.kembalianBayar = kembalianBayar;
    }
    
    /**
     * Creates new form StrukDesign
     */
    public StrukDesign() {
        initComponents();
        body.setBorder(BorderFactory.createEmptyBorder());
    }
    
    public void loadCasherData(){
       String field = "";
       try{
           Statement s = cn.createStatement();
           String query = "SELECT * FROM tb_struk";
           ResultSet rs = s.executeQuery(query);
           
           while(rs.next()){
               String namaBrg = rs.getString("nama");
               int harga = rs.getInt("harga");
               int qty = rs.getInt("quantity");
               int subtotal = rs.getInt("subtotal");
               
               field += "\n " + namaBrg + "\t" + harga + "\t\t" + qty + "\t" + subtotal + " \n";
           }
       } catch (SQLException e){
           System.out.println(e.getMessage());
       }
       System.out.println(field);
       body.setText(field);
       
       totalharga.setText("TOTAL HARGA  : " + String.valueOf(getTotalHarga()));
       totalbayar.setText("TOTAL BAYAR   : " + String.valueOf(getTotalBayar()));
       kembalian.setText("KEMBALIAN    : " + String.valueOf(getKembalianBayar()));
       
       try{
           Statement s = cn.createStatement();
           String query = "DELETE FROM tb_struk";
           s.executeUpdate(query);
       } catch (SQLException e){
           System.out.println(e.getMessage());
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        body = new javax.swing.JTextArea();
        kembalian = new javax.swing.JLabel();
        totalharga = new javax.swing.JLabel();
        totalbayar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("STRUK BELANJA ALAT TULIS KANTOR");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        body.setColumns(20);
        body.setRows(5);
        body.setBorder(null);
        jScrollPane1.setViewportView(body);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 400, 360));

        kembalian.setText("KEMBALIAN   : ");
        add(kembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 530, -1, -1));

        totalharga.setText("TOTAL HARGA  : ");
        add(totalharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 470, -1, -1));

        totalbayar.setText("TOTAL BAYAR   : ");
        add(totalbayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 500, -1, -1));

        jLabel2.setText("TERIMAKASIH TELAH BERBELANJA DI K-ATK");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea body;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel kembalian;
    private javax.swing.JLabel totalbayar;
    private javax.swing.JLabel totalharga;
    // End of variables declaration//GEN-END:variables
}
